version: '3'
services:
  postgres:
    image: postgres:12.7
    container_name: api_website
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test